// The byte-identity parity corpus (PRETRANSPILED_ARTIFACTS_SPEC §4.4 [parity]).
//
// Each entry pairs a fixture file with the sandbox-style absolute `path` it is
// transpiled AS — chain selection depends on the path, so the path is what makes
// a fixture exercise the app-root react-refresh variant vs. the plain/node_modules
// variant. The corpus deliberately covers:
//   - app-root .tsx / .jsx / .js          -> react-refresh chain (HMR wrapped)
//   - app-root .js with `using`            -> explicit-resource-management plugin
//   - app-root .js with require()s         -> dependency collection
//   - app-root .ts                         -> plain chain (no refresh)
//   - /node_modules/ .js                   -> plain chain + compact output
//   - app-root .mdx (frontmatter + GFM)    -> MDX compile + react-refresh chain
//   - app-root .mdx (GitHub admonitions)   -> in-house remark plugin (§12)
//   - app-root .mdx (wiki-links)           -> in-house remark plugin (§13)
//   - app-root .mdx (ESM in links)         -> label-expr / literal-URL / JSX (§14)
//
// Golden outputs live in test/golden/, generated by scripts/gen-golden.mjs from
// THIS package's transformFile and committed as frozen bytes. parity.test.mjs
// re-runs transformFile and asserts byte-for-byte reproduction: any drift in the
// chain (a different Babel/plugin/@mdx-js version, a config edit) breaks the gate.
export const CORPUS = [
  { id: 'app-tsx', file: 'App.tsx', path: '/app/src/App.tsx' },
  { id: 'button-jsx', file: 'Button.jsx', path: '/app/src/Button.jsx' },
  { id: 'entry-js-requires', file: 'entry.js', path: '/app/src/entry.js' },
  { id: 'resource-js-using', file: 'resource.js', path: '/app/src/resource.js' },
  { id: 'helpers-ts-plain', file: 'helpers.ts', path: '/app/src/helpers.ts' },
  { id: 'vendor-js-nodemodules', file: 'vendor.js', path: '/node_modules/acme/index.js' },
  { id: 'post-mdx', file: 'post.mdx', path: '/app/content/post.mdx' },
  { id: 'admonition-mdx', file: 'admonition.mdx', path: '/app/content/admonition.mdx' },
  { id: 'wikilink-mdx', file: 'wikilink.mdx', path: '/app/content/wikilink.mdx' },
  { id: 'esm-links-mdx', file: 'esm-links.mdx', path: '/app/content/esm-links.mdx' },
];
