// GENERATED by scripts/gen-toolchain-hash.mjs — do not edit by hand.
// The §4.4 toolchainHash of the installed @lofcz/transpiler (= the
// published tarball). Regenerated on every build (prebuild). The deploy asserts
// this equals the hash the CLI stamps into artifact indexes (G2-8).

export const EMBEDDED_TOOLCHAIN_HASH = '9b7535cae75431e4a8cbf82e3a7d3029215768504156281f49831c5ef9b9f598';
