#!/usr/bin/env node
/*
 * Bake `TRANSPILER_VERSION` from package.json into `src/version.ts` — the
 * toolchain stamp (PRETRANSPILED_ARTIFACTS_SPEC §4.4) must be the real package
 * version, not a hand-maintained constant that can drift. Runs as `prebuild`;
 * the generated file is committed so node --test and consumers see it without a
 * build, and `version.test.mjs` fails CI if it ever drifts from package.json.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const { version } = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));
const out = join(root, 'src', 'version.ts');
const body =
  `// GENERATED by scripts/gen-version.mjs from package.json — do not edit by hand.\n` +
  `// Regenerated on every build (prebuild); kept honest by version.test.mjs.\n\n` +
  `/**\n` +
  ` * This transpiler's package version — the toolchain stamp (PRETRANSPILED_ARTIFACTS_SPEC §4.4).\n` +
  ` * The version pins the entire per-file transform chain and its configs; the\n` +
  ` * runtime compares it (plus \`toolchainHash\`) against \`index.json\`'s\n` +
  ` * \`toolchain.version\` and ignores all artifacts on mismatch.\n` +
  ` */\n` +
  `export const TRANSPILER_VERSION = '${version}';\n\n` +
  `/**\n` +
  ` * The preset whose chain this package replicates. Part of the stamp: a v1\n` +
  ` * transpiler covers the \`react\` preset only (the immediately.run v1 default).\n` +
  ` */\n` +
  `export const PRESET_NAME = 'react';\n`;

let current = '';
try {
  current = readFileSync(out, 'utf8');
} catch {
  /* first run */
}
if (current !== body) {
  writeFileSync(out, body);
  console.log(`Baked TRANSPILER_VERSION='${version}' -> ${out}`);
} else {
  console.log(`TRANSPILER_VERSION already '${version}' — ${out} unchanged.`);
}
